Update Obfuscate.yml

diff --git a/.github/workflows/Obfuscate.yml b/.github/workflows/Obfuscate.yml
--- a/.github/workflows/Obfuscate.yml
+++ b/.github/workflows/Obfuscate.yml
@@ -35,11 +35,18 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           RELEASE_INFO=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases/latest)
+          RELEASE_INFO2=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/refs/heads/main/RELEASE.md)
           RELEASE_TAG=$(echo "$RELEASE_INFO" | jq -r '.tag_name')
+          RELEASE_TAG2=$(echo "$RELEASE_INFO" | jq -r '.tag_name')
           echo "Latest Release: $RELEASE_TAG"
           DOWNLOAD_URL=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name == "worker.js") | .browser_download_url')
+          DOWNLOAD_URL2=$(echo "$RELEASE_INFO2" | jq -r '.assets[] | select(.name == "worker.js") | .browser_download_url')
           if [ -z "$DOWNLOAD_URL" ]; then
             echo "Error: Could not find worker.js in latest release"
+            exit 1
+          fi
+          if [ -z "$DOWNLOAD_URL2" ]; then
+            echo "Error: Could not find RELEASE.md"
             exit 1
           fi
           echo "Downloading from: $DOWNLOAD_URL"
